/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'blockquote' | 'h4';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type FaqItem = {
  _type: 'faqItem';
  isPinned?: boolean;
  question?: string;
  atomicAnswer?: string;
  detailedAnswer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  targetEntity?: 'Customs' | 'Rates' | 'Timings' | 'Legal' | 'Geography';
  lastReviewed?: string;
};

export type Partner = {
  _id: string;
  _type: 'partner';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  type?: 'carrier' | 'customs' | 'last-mile' | 'hub';
  coveredRegions?: Array<string>;
  websiteUrl?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  author?: AuthorReference;
  topic?: 'customs' | 'packing' | 'rates' | 'news';
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  seoTitle?: string;
  metaDescription?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  experienceYears?: number;
  bio?: string;
  socialProfiles?: Array<string>;
  expertise?: Array<string>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  heroTitlePart1?: string;
  heroTitlePart2?: string;
  heroDescription?: string;
  yearsExp?: string;
  cargoMoved?: string;
  clientsCount?: string;
  destinationsText?: string;
  bodyTitle?: string;
  bodyTitleAccent?: string;
  quoteText?: string;
  quoteAuthor?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  heroTitle?: string;
  heroSubtitle?: string;
  workingHours?: string;
  sidebarTitle?: string;
  sidebarText?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  seoTitle?: string;
  metaDescription?: string;
};

export type RateCard = {
  _id: string;
  _type: 'rateCard';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  cargoType?: string;
  route?: string;
  pricePerKg?: number;
  unitType?: 'KGM' | 'MTQ' | 'C62';
  minWeight?: string;
  transitTime?: string;
  notes?: string;
  lastUpdated?: string;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  slug?: Slug;
  seoTitle?: string;
  metaDescription?: string;
  keywords?: Array<string>;
  serviceType?: 'SeaFreight' | 'AirFreight' | 'MovingCompany' | 'DeliveryService';
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  icon?: string;
  startingPrice?: string;
  rateTable?: Array<{
    item?: string;
    unit?: string;
    price?: string;
    note?: string;
    _type: 'rateRow';
    _key: string;
  }>;
  description?: string;
  keyFeatures?: Array<string>;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  serviceableAreas?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type ContactChannel = {
  _id: string;
  _type: 'contactChannel';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  platform?: 'whatsapp' | 'phone' | 'livechat' | 'webrtc' | 'landline' | 'custom';
  value?: string;
  embedCode?: string;
  priority?: number;
  isActive?: boolean;
};

export type ServiceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'service';
};

export type TrustPointsReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'trustPoints';
};

export type PartnerReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'partner';
};

export type Homepage = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  heroTitle?: string;
  heroSubtitle?: string;
  featuredServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  featuredTrustPoints?: TrustPointsReference;
  featuredPartners?: Array<
    {
      _key: string;
    } & PartnerReference
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  footerText?: string;
};

export type TrustPoints = {
  _id: string;
  _type: 'trustPoints';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  points?: Array<{
    icon?: string;
    heading?: string;
    description?: string;
    _key: string;
  }>;
  shipmentsCount?: string;
  experienceYears?: string;
  warehouseSize?: string;
  safeDeliveryRate?: string;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteUrl?: string;
  title?: string;
  description?: string;
  keywords?: Array<string>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  headerMenu?: Array<{
    label?: string;
    link?: string;
    isButton?: boolean;
    _type: 'navItem';
    _key: string;
  }>;
  footerMenu?: Array<{
    label?: string;
    link?: string;
    _key: string;
  }>;
  gtmId?: string;
  gaId?: string;
  siteVerificationCode?: string;
  semrushCode?: string;
  businessName?: string;
  legalName?: string;
  address?: string;
  geoCoordinates?: Geopoint;
  mainServiceAreas?: Array<string>;
  tradeLicense?: string;
  openingHours?: string;
  phone?: string;
  whatsappNumber?: string;
  socialLinks?: Array<{
    platform?: 'Facebook' | 'Instagram' | 'LinkedIn' | 'Twitter';
    url?: string;
    _key: string;
  }>;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | FaqItem
  | Partner
  | AuthorReference
  | Post
  | Author
  | Slug
  | Page
  | RateCard
  | Service
  | ContactChannel
  | ServiceReference
  | TrustPointsReference
  | PartnerReference
  | Homepage
  | TrustPoints
  | SiteSettings
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../src/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  title,  description,  keywords,  siteUrl,  gtmId,  gaId,  siteVerificationCode,  semrushCode,  businessName,  legalName,  address,  geoCoordinates,  phone,  whatsappNumber,  tradeLicense,  openingHours,  socialLinks,  mainServiceAreas,  headerMenu,  footerMenu,  ogImage {    asset->{ url }  }}
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  keywords: Array<string> | null;
  siteUrl: string | null;
  gtmId: string | null;
  gaId: string | null;
  siteVerificationCode: string | null;
  semrushCode: string | null;
  businessName: string | null;
  legalName: string | null;
  address: string | null;
  geoCoordinates: Geopoint | null;
  phone: string | null;
  whatsappNumber: string | null;
  tradeLicense: string | null;
  openingHours: string | null;
  socialLinks: Array<{
    platform?: 'Facebook' | 'Instagram' | 'LinkedIn' | 'Twitter';
    url?: string;
    _key: string;
  }> | null;
  mainServiceAreas: Array<string> | null;
  headerMenu: Array<{
    label?: string;
    link?: string;
    isButton?: boolean;
    _type: 'navItem';
    _key: string;
  }> | null;
  footerMenu: Array<{
    label?: string;
    link?: string;
    _key: string;
  }> | null;
  ogImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc)
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  slug?: Slug;
  seoTitle?: string;
  metaDescription?: string;
  keywords?: Array<string>;
  serviceType?: 'AirFreight' | 'DeliveryService' | 'MovingCompany' | 'SeaFreight';
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  icon?: string;
  startingPrice?: string;
  rateTable?: Array<{
    item?: string;
    unit?: string;
    price?: string;
    note?: string;
    _type: 'rateRow';
    _key: string;
  }>;
  description?: string;
  keyFeatures?: Array<string>;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  serviceableAreas?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
}>;

// Source: ../src/lib/queries.ts
// Variable: SERVICES_WITH_DETAILS_QUERY
// Query: *[_type == "service"]{  ...,  rateTable,  faqs[] {    question,    atomicAnswer,    detailedAnswer,    lastReviewed  }}
export type SERVICES_WITH_DETAILS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  slug?: Slug;
  seoTitle?: string;
  metaDescription?: string;
  keywords?: Array<string>;
  serviceType?: 'AirFreight' | 'DeliveryService' | 'MovingCompany' | 'SeaFreight';
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  icon?: string;
  startingPrice?: string;
  rateTable: Array<{
    item?: string;
    unit?: string;
    price?: string;
    note?: string;
    _type: 'rateRow';
    _key: string;
  }> | null;
  description?: string;
  keyFeatures?: Array<string>;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  serviceableAreas?: Array<string>;
  faqs: Array<{
    question: string | null;
    atomicAnswer: string | null;
    detailedAnswer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    lastReviewed: string | null;
  }> | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"][0]{  ...,  featuredServices[]->,  featuredTrustPoints->,  featuredPartners[]->,  faqs[] {    question,    atomicAnswer,    detailedAnswer,    lastReviewed  },  seoTitle,  seoDescription,  seoKeywords}
export type HOMEPAGE_QUERY_RESULT = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle: string | null;
  seoDescription: string | null;
  seoKeywords: Array<string> | null;
  heroTitle?: string;
  heroSubtitle?: string;
  featuredServices: Array<{
    _id: string;
    _type: 'service';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    order?: number;
    title?: string;
    slug?: Slug;
    seoTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
    serviceType?: 'AirFreight' | 'DeliveryService' | 'MovingCompany' | 'SeaFreight';
    mainImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    icon?: string;
    startingPrice?: string;
    rateTable?: Array<{
      item?: string;
      unit?: string;
      price?: string;
      note?: string;
      _type: 'rateRow';
      _key: string;
    }>;
    description?: string;
    keyFeatures?: Array<string>;
    details?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    serviceableAreas?: Array<string>;
    faqs?: Array<
      {
        _key: string;
      } & FaqItem
    >;
  }> | null;
  featuredTrustPoints: {
    _id: string;
    _type: 'trustPoints';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    subtitle?: string;
    points?: Array<{
      icon?: string;
      heading?: string;
      description?: string;
      _key: string;
    }>;
    shipmentsCount?: string;
    experienceYears?: string;
    warehouseSize?: string;
    safeDeliveryRate?: string;
  } | null;
  featuredPartners: Array<{
    _id: string;
    _type: 'partner';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    type?: 'carrier' | 'customs' | 'hub' | 'last-mile';
    coveredRegions?: Array<string>;
    websiteUrl?: string;
  }> | null;
  faqs: Array<{
    question: string | null;
    atomicAnswer: string | null;
    detailedAnswer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    lastReviewed: string | null;
  }> | null;
  footerText?: string;
} | null;

// Source: ../src/lib/queries.ts
// Variable: RATE_CARDS_QUERY
// Query: *[_type == "rateCard"] | order(order asc)
export type RATE_CARDS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'rateCard';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  cargoType?: string;
  route?: string;
  pricePerKg?: number;
  unitType?: 'C62' | 'KGM' | 'MTQ';
  minWeight?: string;
  transitTime?: string;
  notes?: string;
  lastUpdated?: string;
}>;

// Source: ../src/lib/queries.ts
// Variable: TRUST_POINTS_QUERY
// Query: *[_type == "trustPoints"][0]
export type TRUST_POINTS_QUERY_RESULT = {
  _id: string;
  _type: 'trustPoints';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  points?: Array<{
    icon?: string;
    heading?: string;
    description?: string;
    _key: string;
  }>;
  shipmentsCount?: string;
  experienceYears?: string;
  warehouseSize?: string;
  safeDeliveryRate?: string;
} | null;

// Source: ../src/lib/queries.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"]
export type PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'partner';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  type?: 'carrier' | 'customs' | 'hub' | 'last-mile';
  coveredRegions?: Array<string>;
  websiteUrl?: string;
}>;

// Source: ../src/lib/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page"]
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  heroTitlePart1?: string;
  heroTitlePart2?: string;
  heroDescription?: string;
  yearsExp?: string;
  cargoMoved?: string;
  clientsCount?: string;
  destinationsText?: string;
  bodyTitle?: string;
  bodyTitleAccent?: string;
  quoteText?: string;
  quoteAuthor?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  heroTitle?: string;
  heroSubtitle?: string;
  workingHours?: string;
  sidebarTitle?: string;
  sidebarText?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  seoTitle?: string;
  metaDescription?: string;
}>;

// Source: ../src/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "page" && _id == "about-us"][0]
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: 'about-us';
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  heroTitlePart1?: string;
  heroTitlePart2?: string;
  heroDescription?: string;
  yearsExp?: string;
  cargoMoved?: string;
  clientsCount?: string;
  destinationsText?: string;
  bodyTitle?: string;
  bodyTitleAccent?: string;
  quoteText?: string;
  quoteAuthor?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  heroTitle?: string;
  heroSubtitle?: string;
  workingHours?: string;
  sidebarTitle?: string;
  sidebarText?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  seoTitle?: string;
  metaDescription?: string;
} | null;

// Source: ../src/lib/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "page" && _id == "contact"][0]
export type CONTACT_PAGE_QUERY_RESULT = {
  _id: 'contact';
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  heroTitlePart1?: string;
  heroTitlePart2?: string;
  heroDescription?: string;
  yearsExp?: string;
  cargoMoved?: string;
  clientsCount?: string;
  destinationsText?: string;
  bodyTitle?: string;
  bodyTitleAccent?: string;
  quoteText?: string;
  quoteAuthor?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  heroTitle?: string;
  heroSubtitle?: string;
  workingHours?: string;
  sidebarTitle?: string;
  sidebarText?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  seoTitle?: string;
  metaDescription?: string;
} | null;

// Source: ../src/lib/queries.ts
// Variable: BLOG_POSTS_LIST_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) {  title,  slug,  mainImage,  publishedAt,  metaDescription,  "authorName": author->name}
export type BLOG_POSTS_LIST_QUERY_RESULT = Array<{
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  publishedAt: string | null;
  metaDescription: string | null;
  authorName: string | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: BLOG_POST_SLUGS_QUERY
// Query: *[_type == "post"]
export type BLOG_POST_SLUGS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  author?: AuthorReference;
  topic?: 'customs' | 'news' | 'packing' | 'rates';
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  seoTitle?: string;
  metaDescription?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
}>;

// Source: ../src/lib/queries.ts
// Variable: AUTHOR_BY_ID_QUERY
// Query: *[_type == "author" && _id == $authorRef][0]
export type AUTHOR_BY_ID_QUERY_RESULT = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  experienceYears?: number;
  bio?: string;
  socialProfiles?: Array<string>;
  expertise?: Array<string>;
} | null;

// Source: ../src/lib/queries.ts
// Variable: RECENT_POSTS_QUERY
// Query: *[_type == "post"] | order(order asc, publishedAt desc)[0...3] {    title,    slug,    mainImage,    publishedAt,    metaDescription,    topic  }
export type RECENT_POSTS_QUERY_RESULT = Array<{
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  publishedAt: string | null;
  metaDescription: string | null;
  topic: 'customs' | 'news' | 'packing' | 'rates' | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: ACTIVE_CONTACT_CHANNELS_QUERY
// Query: *[_type == "contactChannel" && isActive == true] | order(priority asc)
export type ACTIVE_CONTACT_CHANNELS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'contactChannel';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  platform?: 'custom' | 'landline' | 'livechat' | 'phone' | 'webrtc' | 'whatsapp';
  value?: string;
  embedCode?: string;
  priority?: number;
  isActive: true;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  title,\n  description,\n  keywords,\n  siteUrl,\n  gtmId,\n  gaId,\n  siteVerificationCode,\n  semrushCode,\n  businessName,\n  legalName,\n  address,\n  geoCoordinates,\n  phone,\n  whatsappNumber,\n  tradeLicense,\n  openingHours,\n  socialLinks,\n  mainServiceAreas,\n  headerMenu,\n  footerMenu,\n  ogImage {\n    asset->{ url }\n  }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "service"] | order(order asc)': SERVICES_QUERY_RESULT;
    '*[_type == "service"]{\n  ...,\n  rateTable,\n  faqs[] {\n    question,\n    atomicAnswer,\n    detailedAnswer,\n    lastReviewed\n  }\n}': SERVICES_WITH_DETAILS_QUERY_RESULT;
    '*[_type == "homepage"][0]{\n  ...,\n  featuredServices[]->,\n  featuredTrustPoints->,\n  featuredPartners[]->,\n  faqs[] {\n    question,\n    atomicAnswer,\n    detailedAnswer,\n    lastReviewed\n  },\n  seoTitle,\n  seoDescription,\n  seoKeywords\n}': HOMEPAGE_QUERY_RESULT;
    '*[_type == "rateCard"] | order(order asc)': RATE_CARDS_QUERY_RESULT;
    '*[_type == "trustPoints"][0]': TRUST_POINTS_QUERY_RESULT;
    '*[_type == "partner"]': PARTNERS_QUERY_RESULT;
    '*[_type == "page"]': PAGE_SLUGS_QUERY_RESULT;
    '*[_type == "page" && _id == "about-us"][0]': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "page" && _id == "contact"][0]': CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "post"] | order(publishedAt desc) {\n  title,\n  slug,\n  mainImage,\n  publishedAt,\n  metaDescription,\n  "authorName": author->name\n}': BLOG_POSTS_LIST_QUERY_RESULT;
    '*[_type == "post"]': BLOG_POST_SLUGS_QUERY_RESULT;
    '*[_type == "author" && _id == $authorRef][0]': AUTHOR_BY_ID_QUERY_RESULT;
    '*[_type == "post"] | order(order asc, publishedAt desc)[0...3] {\n    title,\n    slug,\n    mainImage,\n    publishedAt,\n    metaDescription,\n    topic\n  }': RECENT_POSTS_QUERY_RESULT;
    '*[_type == "contactChannel" && isActive == true] | order(priority asc)': ACTIVE_CONTACT_CHANNELS_QUERY_RESULT;
  }
}
